# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ghorvath <ghorvath@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/06/07 07:52:25 by ghorvath          #+#    #+#              #
#    Updated: 2021/06/13 07:44:18 by ghorvath         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC				=	gcc
FLAGS			=	-Wall	-Wextra	-Werror
NAME			=	ft_display_file
SRC				=	ft_display_file.c

all:	$(NAME)

$(NAME):

	$(CC)	$(FLAGS)	$(SRC)	-o	$(NAME)

clean:

	rm	-f	$(NAME)

fclean:	clean

	/bin/rm	-f	$(NAME)

re:	fclean	all
